[Global]
// Forza la shell predefinita per gli utenti di dominio che effettuano l'accesso
template shell = /bin/bash

// Nome NetBIOS del dominio Active Directory
workgroup = LAB

// Imposta Samba in modalità membro nativo di un dominio Active Directory (Active Directory Services)
security = ADS

// Specifica il Realm Kerberos in lettere MAIUSCOLE, indispensabile per il funzionamento del trust ticket
realm = LAB.LOCAL

// Integrazione del sottosistema di stampa (CUPS) per la condivisione di stampanti in rete
printing = cups
printcap name = cups
load printers = yes

// Permette di omettere il prefisso del dominio (es. 'utente' invece di 'LAB\utente') nei comandi Linux
winbind use default domain = yes

// Abilita l'enumerazione completa degli utenti e gruppi AD tramite winbind.
// Necessario per la risoluzione locale con getent, ma sconsigliato in domini con molti oggetti
winbind enum users = yes
winbind enum groups = yes
winbind expand groups = 4

// Configurazione del backend IDMAP per la mappatura dei SID di Windows in UID/GID di Linux
// Definisce l'intervallo di allocazione degli ID locali (da 3000 a 79999) tramite database TDB locale
idmap config * : backend = tdb
idmap config * : range = 3000-79999


[Printers]
// Configurazione di default per l'esposizione automatica delle stampanti di sistema
comment = All Printers
path = /var/spool/samba
browseable = yes
printable = yes
guest ok = yes
read only = yes


[Print$]
// Area di storage per i driver delle stampanti condivise Windows
path= /var/lib/samba/printers
browseable = yes
read only = yes


[ProgettiDev]
// --- CONDIVISIONE IBRIDA APPLICATIVA ---
// Percorso fisico sul file system locale di Debian
path = /srv/samba/progetti_dev

// SBARRAMENTO DI SICUREZZA: Solo gli utenti appartenenti al gruppo globale "G_Sviluppatori" 
// censito dentro Windows Active Directory possono accedere a questa cartella.
valid users = @"LAB\G_Sviluppatori"
read only = no
guest ok = no


[dev_share]
// --- CONDIVISIONE LOCALE DI PROVVISORIA ---
path = /srv/samba/dev
read only = no
browseable = yes
valid users = @smb_dev_share
// Forza l'appartenenza dei file creati al gruppo di sviluppo locale
force groups = smb_dev_share
// Maschere restrittive sui permessi (POSIX): File in 660, directory con Sticky Bit e SGID in 2770
create mask = 0660
directory mask = 2770
